// Code generated by MockGen. DO NOT EDIT.
// Source: generator.go
//
// Generated by this command:
//
//	mockgen -source=generator.go -destination=./generator_mock.go -package=uuid -mock_names Generatorable=Mock
//

// Package uuid is a generated GoMock package.
package uuid

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// Mock is a mock of Generatorable interface.
type Mock struct {
	ctrl     *gomock.Controller
	recorder *MockMockRecorder
}

// MockMockRecorder is the mock recorder for Mock.
type MockMockRecorder struct {
	mock *Mock
}

// NewMock creates a new mock instance.
func NewMock(ctrl *gomock.Controller) *Mock {
	mock := &Mock{ctrl: ctrl}
	mock.recorder = &MockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mock) EXPECT() *MockMockRecorder {
	return m.recorder
}

// UUID mocks base method.
func (m *Mock) UUID() uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UUID")
	ret0, _ := ret[0].(uuid.UUID)
	return ret0
}

// UUID indicates an expected call of UUID.
func (mr *MockMockRecorder) UUID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UUID", reflect.TypeOf((*Mock)(nil).UUID))
}
